name: hello
on:
  push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run a one-line script
        run: echo "Hello, world"
      - name: build giftcardreader 
        run: gcc  giftcardreader.c -o giftcardreader
      - name: Run crash 1
        run: ./giftcardreader 1 part2/crash1.gft
      - name: Run crash 2     
        run: ./giftcardreader 1 part2/crash2.gft
      - name: Run crash 3     
        run: ./giftcardreader 1 part2/hang.gft